runtime: php72

handlers:
# Serve a directory as a static resource.
- url: /styles
  static_dir: styles
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  
# Serve your app through a front controller at index.php or public/index.php.
- url: /(.+\.php)$
  static_files: static/\1
  upload: /(.+\.php)$

- url: .*
  script: auto
  secure: always
